services:
  redis:
    networks:
      - default

  postgres:
    networks:
      - default

  taxhub:
    networks:
      - default
      - traefik
    labels:
      - "traefik.docker.network=traefik"
      - "traefik.http.routers.taxhub.middlewares=hardening@docker"

  usershub:
    networks:
      - default
      - traefik
    labels:
      - "traefik.docker.network=traefik"
      - "traefik.http.routers.usershub.middlewares=hardening@docker"

  geonature-backend:
    networks:
      - default
      - traefik
    labels:
      - "traefik.docker.network=traefik"
      - "traefik.http.routers.geonature-backend.middlewares=hardening@docker"

  geonature-frontend:
    networks:
      - default
      - traefik
    labels:
      - "traefik.docker.network=traefik"
      - "traefik.http.routers.geonature.middlewares=hardening@docker"

  geonature-install-db:
    networks:
      - default

  geonature-worker:
    networks:
      - default

networks:
  traefik:
    external: true